package uy.com.md.common.enumerated;

public enum OperacionTipo {
    SOLICITUD_NOMINADA, RECARGA, ENTREGA_NOMINADA, MOVIMIENTOS, TRANSFERENCIA_C2C, PAGO_SERVICIOS, TRANSFERENCIA_C2B, ALTA_TRANSFERENCIA, RECARGA_ATM_CUMPLIMIENTO, SOLICITUD_INNOMINADA, REPOSICION_INNOMINADA;
}
